### PR TITLE
fixed color name typo

### PR DESCRIPTION
**Pull request by olafk**
(most likely to be carried over to the other build-options)

### CODE REVIEW

**Comment by gamerson** [comment]
Thanks @olafk  ! @lawrence-lee  can you replicate to other environments?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lawrence-lee** [comment]
Just started reviewing :)

**Comment by lawrence-lee** [comment]
Merged!

**Pull request closed without merging**
