### PR TITLE
Add projects to settings.gradle

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @gamerson, I always forget... what's the relation between this and the `project-templates-*` ones in https://github.com/liferay/liferay-portal/tree/master/modules/sdk

Should we be creating templates there as well?

**Comment by rafoli** [comment]
Hi @izaera,

Could I run and test this PR with yours npm-* samples using Liferay 7.0?
I've seen a warning in your repo: https://github.com/izaera/liferay-npm-examples#warning

**Comment by jbalsas** [comment]
Hey @rafoli, the idea is that you should be able to use them in newer releases of `7.0`, SP5 and GA5 once they get out.

For now, you could try it out on the master branch.

**Comment by rafoli** [comment]
Great! Thanks @jbalsas

**Comment by gamerson** [comment]
hey @jbalsas  the *samples* are just that, samples that are hoping to demostrate one thing (or a number of related things), and they can just be only slightly different between samples.  Like multiple angular js samples, or multiple service builder samples (that show slightly different concepts, etc)

The ones in /modules/sdk/project-templates-* those are archetypes.  So there wouldn't be multiple angular js templates, just one template.  Whereas in blade samples we might have 5 angularjs samples (each one something something slightly different).

So # of project templates should always be less then # of project samples.  Does this make since? 

Its like the 'samples' are instances of 'templates'.  prototype versus instantiated object, etc. :) I hope i'm not belaboring the point.

**Comment by jbalsas** [comment]
Aaah, I see, then what we wanted to do was to create those `templates`,  so people could do the `blade create -t react-portlet`?

**Comment by gamerson** [comment]
now @jbalsas  what we would likely try to do, is make some of these samples 'generic' and convert them to a template that coudl be installed from blade cli.  

The samples are meant to make it easy for developers to copy&paste or see embedded documentation.  Where the project templates would not have so much embedded documentation.

**Comment by gamerson** [comment]
hey @jbalsas  right you want project-templates-*

however, this is good to start them here.  We can use the samples repo as proving grounds that we all agree this is the right structure to demostrate the usage.  Then once we get it working for both maven and gradle, we can begin to build the archetypes (project-templates-*) which is a little more involved.  I can show you guys how to do that so you can help contribute it there as well.  (Creating a archetype with all the velocity variables, etc) is a bit more involved but not too bad.

**Comment by gamerson** [comment]
thanks @izaera  for sending these across, looking forward to seeing them be templates!

**Comment by jbalsas** [comment]
sounds good, @izaera will coordinate with you to see those brought to templates!! 💪

**Comment by gamerson** [comment]
so @izaera  before these can be templates we want to have the maven equivalents for each of these builds.  If there are blockers with the maven equivalence (missing or badly behaving npm plugins) we can always drop the maven requirement initially to get the gradle templates available in people's hands sooner than later.

**Comment by izaera** [comment]
OK, cool. Feel free to ask me for any help you may need.

**Comment by gamerson** [comment]
hey guys, this has now been sent here: https://github.com/gamerson/liferay-blade-samples/pull/369

We don't have the maven piece right now, but we can add that later.  Also, I may have broken some things when I refactored.  Could you double check @izaera ?  I'll go ahead and merge it and you can send me a new pull with any fixes.

Thanks!

**Pull request closed without merging**
